SimpleSurveyApp/urls.py
from django.urls import path

from .views import question_view, response_view, FormsubmitView, certificate_view,SearchListView
from . import views

app_name = 'SimpleSurveyApp'

urlpatterns = [
    path('', views.dynamicquestions, name='home'),
    path('responses/', views.dynamicresponses, name='feedback'),
    path('api/questions/', question_view, name='question-list'),
    path('api/questions/response/', response_view, name='fetch-responses'),
    path('api/questions/responses/', FormsubmitView.as_view(), name='submit-responses'),
    path('api/questions/responses/certificates/<int:pk>/',certificate_view, name='certificate-list'),
    path('search/', SearchListView.as_view(), name='search-list'),
    path('successful/', views.success_message, name='success'),
    path('error/<str:search_param>/', views.search_error, name='error_page'),

]

SimpleSurveyApplication/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('SimpleSurveyApp.urls')),
    path('admin/', admin.site.urls),
]

SimpleSurveyApp/models.py
from django.db import models

GENDER_CHOICES = [
    ('MALE', 'male'),
    ('FEMALE', 'female'),
    ('OTHER', 'other'),
]
PROGRAMMING_STACK_CHOICES = [
    ('REACT', 'React Js'),
    ('ANGULAR', 'Angular Js'),
    ('VUE', 'Vue Js'),
    ('SQL', 'Sql'),
    ('POSTGRES', 'Postgres'),
    ('MYSQL', 'Mysql'),
    ('JAVA', 'Java'),
    ('PHP', 'Php'),
    ('GO', 'Go'),
    ('RUST', 'Rust'),

]


class Question(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=50)
    required = models.BooleanField(blank=False)
    text = models.TextField(max_length=300)
    description = models.TextField(max_length=255)


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    G_value = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True)
    PS_value = models.CharField(max_length=50, choices=PROGRAMMING_STACK_CHOICES, blank=True)


class SurveyResponse(models.Model):
    full_name = models.CharField(max_length=255)
    email_address = models.EmailField(max_length=30)
    description = models.TextField(max_length=500)
    gender = models.CharField(max_length=10, )
    programming_stack = models.CharField(max_length=20, blank=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    date_responded = models.DateTimeField(auto_now_add=True)
    my_certs = models.FileField(blank=False)

SimpleSurveyApp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, parser_classes
from rest_framework.views import APIView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Question, SurveyResponse
from rest_framework.parsers import MultiPartParser, FormParser, JSONParser
from .serializers import QuestionSerializer, SurveyResponseSerializer
from django.http import HttpResponse
import django_filters.rest_framework
from rest_framework import generics
from django.contrib import messages
from rest_framework import filters
from django.template import loader
import requests
from django.db import models


@api_view(['GET'])
def question_view(request):
    try:
        questions = Question.objects.all()
    except Question.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)


def dynamicquestions(request):
    api_url = 'http://127.0.0.1:8000/api/questions/'

    try:
        response = requests.get(api_url)
        response.raise_for_status()
        questions = response.json()

        sorted_questions = sorted(questions, key=lambda x: x['id'])

    except requests.exceptions.RequestException as e:
        sorted_questions = []
        print(f"Error fetching questions: {e}")

    return render(request, 'Form.html', {'questions': sorted_questions})


class FormsubmitView(APIView):
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = SurveyResponseSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return redirect('SimpleSurveyApp:success')

        return Response(
            serializer.errors,
            status=status.HTTP_400_BAD_REQUEST
        )


@api_view(['GET'])
def response_view(request):
    try:
        responses = SurveyResponse.objects.all()
    except SurveyResponse.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method == 'GET':
        serializer = SurveyResponseSerializer(responses, many=True)
        return Response(serializer.data)


def dynamicresponses(request):
    api_url = 'http://127.0.0.1:8000/api/questions/response/'

    try:
        # Fetch responses from the DRF API
        response = requests.get(api_url)
        response.raise_for_status()
        responses = response.json()

        sorted_responses = sorted(responses, key=lambda x: x['id'])
        paginator = Paginator(sorted_responses, 3)
        page = request.GET.get('page')
        try:
            paginated_responses = paginator.page(page)
        except PageNotAnInteger:
            paginated_responses = paginator.page(1)
        except EmptyPage:
            paginated_responses = paginator.page(paginator.num_pages)
    except requests.exceptions.RequestException as e:

        paginated_responses = []
        print(f"Error fetching responses: {e}")

    return render(request, 'Response.html', {'responses': paginated_responses})


@api_view(['GET'])
def certificate_view(request, pk):
    try:
        survey_response = SurveyResponse.objects.get(pk=pk)
    except SurveyResponse.DoesNotExist:
        return Response({'detail': 'Certificate not found.'}, status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        if survey_response.my_certs:
            file_path = survey_response.my_certs.path
            with open(file_path, 'rb') as file:
                response = HttpResponse(file.read(), content_type='application/pdf')
                response['Content-Disposition'] = f'attachment; filename="{survey_response.my_certs.name}"'
                return response
        else:
            return Response({'detail': 'Certificate not found.'}, status=status.HTTP_404_NOT_FOUND)


class SearchListView(generics.ListAPIView):
    queryset = SurveyResponse.objects.all()
    serializer_class = SurveyResponseSerializer
    filter_backends = [django_filters.rest_framework.DjangoFilterBackend]
    filterset_fields = ['email_address']

    def get(self, request, *args, **kwargs):
        search_param = request.GET.get('search')

        if not search_param:
            return redirect('SimpleSurveyApp:feedback')
        queryset = self.queryset.filter(email_address__icontains=search_param)
        if not queryset.exists():
            return redirect('SimpleSurveyApp:error_page', search_param)

        serializer = self.get_serializer(queryset, many=True)
        context = {'responses': serializer.data, 'search_query': search_param}
        return render(request, 'Response.html', context)


def success_message(request):
    return render(request, 'Success.html')


def search_error(request, search_param):
    context = {
        'search_param': search_param,
    }
    return render(request, 'errorsearch.html', context)

templates/Form.html
{% extends "master.html" %}
{% load static %}
{% block additionalStyles %}
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/form.css' %}">

{% endblock %}
{% block content %}
<form id="regForm" action="http://127.0.0.1:8000/api/questions/responses/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Survey Form</h1>
    <div id="questions-container">
        {% for question in questions %}
            <div class="tab">
                <h3>Step {{question.id}} : {{ question.text }}</h3>
                {% if question.type == "short_text" %}
                    <input type="text" name="{{ question.name }}" placeholder="Enter your first and lastname" required>
                {% elif question.type == "email" %}
                    <input type="email" name="{{ question.name }}" required>
                {% elif question.type == "long_text" %}
                    <textarea name="{{ question.name }}" required></textarea>
                {% elif question.type == "choice" %}
                    {% for choice in question.choices%}
                        <label><input type="radio"  name="{{ question.name }}" value="{{ choice.G_value }}" required/> {{ choice.G_value }}</label>
                    {% endfor %}
                {% elif question.type == "file" %}
                    <input type="file" name="{{ question.name }}" multiple = "multiple" accept=".pdf"/>
                {% elif question.type == "choices" %}
                    <select name="{{ question.name }}" multiple="multiple" required>
                        {% for choice in question.choices%}
                            <option value="{{ choice.PS_value }}">{{ choice.PS_value }}</option>
                        {% endfor %}
                    </select>
                {% endif %}

                <p style="color:red">{{ question.description }}</p>
            </div>
        {% endfor %}
    </div>

    <div style="overflow:auto;">
        <div style="float:right;">
            <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
            <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
            <button type="submit" id="submitBtn" style="display:none;">Submit</button>
        </div>
    </div>


    <div style="text-align:center;margin-top:40px;">
        {% for question in questions %}
            <span class="step"></span>
        {% endfor %}
    </div>
</form>

{% endblock %}
{% block extra_scripts %}
<script src="{% static 'js/form.js' %}"></script>
{% endblock %}

templates/Response.html
{% extends "master.html" %}
{% load static %}

{% block additionalStyles %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
{% endblock %}
{% block content %}

<form method="get" action="{% url 'SimpleSurveyApp:search-list' %}">
    <input type="text" name="search" id="myInput" value="{{search_query}}" placeholder="Search by Email Address" title="Type in email">
    <button type="submit" id="searchButton" >Search</button>
</form>


<div style="overflow-x:auto;">
    <table id="myTable">
        <tr class="header">
            <th style="width:15%;">Full Name</th>
            <th style="width:15%;">Email Address</th>
            <th style="width:15%;">Description</th>
            <th style="width:10%;">Gender</th>
            <th style="width:15%;">Programming Stack</th>
            <th style="width:15%;">Data Responded</th>
            <th style="width:15%;">Certificates</th>
        </tr>
        {% if search_query %}
            {% for response in responses %}
                    <tr>
                        <td>{{ response.full_name }}</td>
                        <td>{{ response.email_address }}</td>
                        <td>{{ response.description }}</td>
                        <td>{{ response.gender }}</td>
                        <td>{{ response.programming_stack }}</td>
                        <td>{{ response.date_responded }}</td>
                        <td>{{ response.my_certs }}</td>
                    </tr>

            {% endfor %}
        {% else %}
            {% for response in responses %}
                <tr>
                    <td>{{ response.full_name }}</td>
                    <td>{{ response.email_address }}</td>
                    <td>{{ response.description }}</td>
                    <td>{{ response.gender }}</td>
                    <td>{{ response.programming_stack }}</td>
                    <td>{{ response.date_responded }}</td>
                    <td>{{ response.my_certs }}</td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
</div>

<div class="pagination">
    <span class="step-links">
        {% if responses.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ responses.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ responses.number }} of {{ responses.paginator.num_pages }}.
        </span>

        {% if responses.has_next %}
            <a href="?page={{ responses.next_page_number }}">next</a>
            <a href="?page={{ responses.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

templates/Success.html
{% extends "master.html" %}
{% load static %}

{% block additionalStyles %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<style>
   .container {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    text-align: center;
}

h1 {
    font-size: 24px;
    margin-bottom: 20px;
}

p {
    font-size: 20px;
    line-height: 1.5;
    margin-bottom: 20px;
}

.btn {
    display: inline-block;
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border: none;
    cursor: pointer;
}

@media (max-width: 600px) {
    .container {
        width: 90%;
    }

    h1 {
        font-size: 20px;
    }

    p {
        font-size: 16px;
    }

    .btn {
        font-size: 12px;
        padding: 5px 10px;
    }
}


</style>
{% endblock %}
{% block content %}
<div class="container">
    <h1>Success!</h1>
    <p>Your responses have been successfully saved,view your responses in Survey Responses! </p>
    <a href="{% url 'SimpleSurveyApp:home' %}" class="btn">Go Back to Survey Form </a>
</div>
{% endblock %}

templates/errorsearch.html
{% extends "master.html" %}
{% load static %}

{% block additionalStyles %}
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<style>
   .container {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    text-align: center;
}

h1 {
    font-size: 24px;
    margin-bottom: 20px;
}

p {
    font-size: 20px;
    line-height: 1.5;
    margin-bottom: 20px;
}

.btn {
    display: inline-block;
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border: none;
    cursor: pointer;
}

@media (max-width: 600px) {
    .container {
        width: 90%;
    }

    h1 {
        font-size: 20px;
    }

    p {
        font-size: 16px;
    }

    .btn {
        font-size: 12px;
        padding: 5px 10px;
    }
}


</style>
{% endblock %}
{% block content %}
<div class="container">
    <h1>Sorry!</h1>
    <p>Oops! nothing matched the search item :<b> '{{ search_param}}'</b></p>
    <a href="{% url 'SimpleSurveyApp:feedback' %}" class="btn">Go Back to Survey Response </a>
</div>
{% endblock %}

templates/master.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Survey Application</title>
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
     <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
     <link rel="icon" type="image" href="{% static 'images/surveyicon.png' %}">

     {% block additionalStyles %}{% endblock %}
</head>

<body>
  <nav>
      <input type="checkbox" id="check">
      <label for="check" class="checkbutton">
          <i class="fas fa-bars"></i>
      </label>
      <label class="logo">Survey</label>
      <ul>
          <li><a class="active" href="{% url 'SimpleSurveyApp:home' %}" >Survey Form</a> </li>
          <li><a href="{% url 'SimpleSurveyApp:feedback' %}" >Survey Response</a> </li>
      </ul>
  </nav>
{% block content %}
{% endblock %}
{% block extra_scripts %}{% endblock %}
</body>
</html>